version: '3'
services:

  postgres-mvp:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "mvp"
      POSTGRES_PASSWORD: "mvp"
      POSTGRES_DB: "mvp"

  mvp-service:
    image: "mvp-service:latest"
    ports:
      - "8080:8080"
    restart: no
    build:
      context: mvp-service
      dockerfile: ./Dockerfile
    depends_on:
      - postgres-mvp
    environment:
      DATABASE_HOST: postgres-mvp
      DATABASE_PORT: 5432
      DATABASE_USERNAME: mvp
      DATABASE_PASSWORD: mvp
      DATABASE_NAME: mvp
